isqcuat> db.sqmarcherkeycontrol.find({UniqueControlID:'AME-RC-NTW-412',FiscalYear: 'FY26'})
[
  {
    _id: ObjectId('69e763dd0aae8818d7ec1eca'),
    ActiveQualityRiskUniqueIds: 'QR-NTW-87',
    ActiveQualitySubRiskUniqueIds: '',
    AdditionalQOs: [],
    AdditionalQRs: [],
    ArcherPublishedOn: '2026-04-21T11:44:33.375Z',
    AreaId: 'AME',
    BusinessUnitId: '',
    ClusterId: '',
    ControlCriteria: ' The archive notification rules are reviewed and approved to ensure that they are configured in line with the applicable requirements.',
    ControlCriteriaLocal: '',
    ControlDescription: 'Annually, rules set up in ARC for automated notifications are reviewed and validated against the appropriate requirements.\n' +
      '\n' +
      'If differences are identified, then actions are taken to update those notifications that may have an incorrect rule set for them.',
    ControlDescriptionLocal: '',
    ControlDesignedByName: 'NETWORK',
    ControlDesignedByType: 'Network',
    ControlName: 'Annual review and verification of ARC Notification Management configuration',
    ControlNameLocal: '',
    ControlNature: 'Detect',
    ControlObjective: ' To evaluate if the archive notification rules in ARC match the applicable requirements.',
    ControlObjectiveLocal: '',
    ControlOperatorTitleAssignments: '',
    ControlOperatorTitleIDs: '',
    ControlOperatorTitles: '',
    ControlOwnerProceduresOverCompleteness: 'IEC-ID-232915:',
    ControlOwnerProceduresOverCompletenessLocal: '',
    ControlOwnerTitleAssignments: '',
    ControlOwnerTitles: 'Region ARC Coordinator',
    ControlOwnerTitlesIDs: '6855d87f71835f94ed69e8db',
    ControlType: 'IT Dependent Manual',
    ControlsByPeriod: 'Control added in FY26',
    Draft: false,
    EngagementType: '',
    EntityFiscalYear: 2026,
    EntityId: 'AME',
    EntityType: 'Area',
    ExecutingEntity: 'Americas',
    FirmPublishedDate: '2026-04-20T15:07:56.671Z',
    FiscalYear: 'FY26',
    Frequency: 'Annually',
    FunctionBaselineControlDesign: '6855d87271835f94ed69e550',
    FunctionBaselineControlExecution: '6855d87171835f94ed69e528',
    FunctionBaselineLocalControlDesign: '6855d87471835f94ed69e5ca',
    FunctionId: '6855d87171835f94ed69e528',
    FunctionOwnerAssignments: 'Katrina.Kimpel@ey.com',
    FunctionOwnerTitle: 'Americas Vice Chair – Professional Practice',
    IEC: 'IEC-ID-232915:ARC Notification Centre',
    IECIDs: '232915',
    IECLocal: null,
    IECRationale: 'TBD',
    IECRationaleLocal: '',
    IECReportType: 'IEC-ID-232915:Modifiable',
    IECSystems: 'IEC-ID-232915:TECH-NTW-IS: ARC (Archive Records Center)',
    IsControlOverResource: true,
    IsControlOverResourceNew: 'Yes',
    IsQoOverrideEnabled: '',
    IsThisIECReportOrOther: 'IEC-ID-232915:Other',
    KeyControlOperatedByServiceProvider: false,
    KeyControlOperatedByServiceProviderNew: 'No',
    LastProcessedDate: '2026-04-21T11:44:33.375Z',
    LocalLanguage: '',
    MemberFirmId: '',
    NetworkId: '',
    PCAOB_Configured_Object: 'No',
    PerformedOnBehalfOf: 'United States of America; Uruguay; Colombia; Chile; Aruba; Panama; Venezuela; Paraguay; Costa Rica; Ecuador; Mexico; Jamaica; Bermuda; Peru; Israel; Cayman Islands; El Salvador; Curacao; Trinidad and Tobago; Honduras; Bolivia; Dominican Republic; Guatemala; Argentina; Barbados; Brazil; Suriname; Bahamas; St. Lucia; Nicaragua; Guyana',
    ProcessId: [ ObjectId('6855d87171835f94ed69e50f') ],
    ProcessUniqueId: 'PR-06',
    QualityObjectiveUniquesIds: '',
    Ref_UniqueId: 'RC-NTW-412',
    RegionId: '',
    RelatedPolicyProcedureManualGuidance: ' TBD',
    RelatedPolicyProcedureManualGuidanceLocal: '',
    ResourceIds: '6855d8d871835f94ed69edbe',
    ResourceName: 'TECH-NTW-IS: ARC (Archive Records Center)',
    ResourceType: 'Technology',
    ServiceLine: '',
    ServiceProviderName: '',
    ServiceProviderNameLocal: '',
    SubClusterId: '',
    SupportingEvidence: '1. Confirmation of review, any changes as a result of the review and relevant requirements; 2. Screenshots showing notification setting is turned "on" and is set to "archive due in 7, 15 or 30 days"',
    SupportingEvidenceLocal: '',
    SupportingITApplication: 'TECH-NTW-IS: ARC (Archive Records Center)',
    Tags: '',
    UniqueControlID: 'AME-RC-NTW-412',
    qualityObjectiveUniqueIdArray: [ 'QO-NTW-33' ],
    qualityRiskUniqueIdArray: [ 'QR-NTW-87' ],
    qualitySubRiskUniqueIdArray: [],
    FunctionName: 'Professional Practice',
    FunctionOwnerTitleId: [ ObjectId('6904f99d65291dda74fa3a44') ],
    RejectedQualityRiskUniqueIds: '',
    RejectedSubQualityRiskUniqueIds: null,
    EventAction: 'Update',
    EventDate: '2026-03-27T11:02:54.492Z',
    EventType: 'New',
    LastPublishedRecordStatus: 'Active'
  }
]

isqcuat> db.sqmarcherkeycontrol.find({UniqueControlID:'NZ-RC-NTW-15',FiscalYear: 'FY26'})
[
  {
    _id: ObjectId('69e763dd0aae8818d7ec1ecf'),
    ActiveQualityRiskUniqueIds: 'QR-NTW-07;QR-NTW-01;QR-NTW-02;QR-NTW-14;QR-NTW-10;QR-NTW-03;QR-NTW-08',
    ActiveQualitySubRiskUniqueIds: '',
    AdditionalQOs: [],
    AdditionalQRs: [],
    ArcherPublishedOn: '2026-04-21T11:44:33.375Z',
    AreaId: '',
    BusinessUnitId: '',
    ClusterId: '',
    ControlCriteria: ' - Responses received about how personnel experience the firm’s culture and values and leadership are reviewed and approved to determine next steps (e.g., themes, trends) that emerge from the responses.\n' +
      '- Monitoring over the effectiveness of the actions taken to improve targeted quality-related area\n' +
      '\n',
    ControlCriteriaLocal: '',
    ControlDescription: 'CMP reviews and approves actions designed to respond to information about how personnel experience the firm’s culture and values, and leadership.\n',
    ControlDescriptionLocal: '',
    ControlDesignedByName: 'NETWORK',
    ControlDesignedByType: 'Network',
    ControlName: 'Approval of actions designed to respond to information about how personnel experience the firm’s culture and values, and leadership.',
    ControlNameLocal: '',
    ControlNature: 'Detect',
    ControlObjective: ' To review the responses received about how personnel experience the firm’s culture and values and leadership and to execute appropriate follow-up initiatives.\n' +
      'To inform action in response to responses received about how personnel experience the firm’s culture and values and leadership\n',
    ControlObjectiveLocal: '',
    ControlOperatorTitleAssignments: 'Bridget.Brockelbank@nz.ey.com;Emma.Winsloe@nz.ey.com',
    ControlOperatorTitleIDs: '6855d87871835f94ed69e6e4;69a4f8a82e15ccca137da1ef',
    ControlOperatorTitles: 'Country QEL;Country Assurance People Leader',
    ControlOwnerProceduresOverCompleteness: null,
    ControlOwnerProceduresOverCompletenessLocal: null,
    ControlOwnerTitleAssignments: 'nicole.odonnell@ey.com',
    ControlOwnerTitles: 'Country Managing Partner',
    ControlOwnerTitlesIDs: '6855d87771835f94ed69e686',
    ControlType: 'Manual',
    ControlsByPeriod: 'Rolled forward Control',
    Draft: false,
    EngagementType: 'Reviews of financial statements;Other Assurance;Audit of financial statements;Agreed upon procedures;Compilation',
    EntityFiscalYear: 2026,
    EntityId: 'NZ',
    EntityType: 'Location',
    ExecutingEntity: 'New Zealand',
    FirmPublishedDate: '2026-04-16T13:17:08.311Z',
    FiscalYear: 'FY26',
    Frequency: 'Annually',
    FunctionBaselineControlDesign: '6855d87471835f94ed69e5aa',
    FunctionBaselineControlExecution: '6855d87371835f94ed69e569',
    FunctionBaselineLocalControlDesign: '6855d87371835f94ed69e569',
    FunctionId: '6855d87371835f94ed69e569',
    FunctionOwnerAssignments: 'nicole.odonnell@ey.com',
    FunctionOwnerTitle: 'Country Managing Partner',
    IEC: 'IEC Name: Results of the responses received about how personnel experience the firm’s culture and values and leadership \n' +
      '\n',
    IECIDs: '',
    IECLocal: '',
    IECRationale: '',
    IECRationaleLocal: '',
    IECReportType: '',
    IECSystems: '',
    IsControlOverResource: false,
    IsControlOverResourceNew: 'No',
    IsQoOverrideEnabled: '',
    IsThisIECReportOrOther: '',
    KeyControlOperatedByServiceProvider: false,
    KeyControlOperatedByServiceProviderNew: 'No',
    LastProcessedDate: '2026-04-21T11:44:33.375Z',
    LocalLanguage: '',
    MemberFirmId: 'NZ',
    NetworkId: '',
    PCAOB_Configured_Object: 'No',
    PerformedOnBehalfOf: 'New Zealand',
    ProcessId: [ ObjectId('6855d87271835f94ed69e548') ],
    ProcessUniqueId: 'PR-98',
    QualityObjectiveUniquesIds: '',
    Ref_UniqueId: 'RC-NTW-15',
    RegionId: '',
    RelatedPolicyProcedureManualGuidance: ' SQM ROLES',
    RelatedPolicyProcedureManualGuidanceLocal: '',
    ResourceIds: '',
    ResourceName: '',
    ResourceType: '',
    ServiceLine: 'GDS; Tax; Strategy and Transactions; Consulting; Assurance',
    ServiceProviderName: '',
    ServiceProviderNameLocal: '',
    SubClusterId: '',
    SupportingEvidence: 'Results of the responses received about how personnel experience the firm’s culture and values and leadership; Evidence of review and approval of the results (e.g., themes/trends), including monitoring the effectiveness of actions taken based on responses received ',
    SupportingEvidenceLocal: '',
    SupportingITApplication: '',
    Tags: '',
    UniqueControlID: 'NZ-RC-NTW-15',
    qualityObjectiveUniqueIdArray: [ 'QO-NTW-01', 'QO-NTW-02', 'QO-NTW-05', 'QO-NTW-06', 'QO-NTW-36' ],
    qualityRiskUniqueIdArray: [
      'QR-NTW-07',
      'QR-NTW-01',
      'QR-NTW-02',
      'QR-NTW-14',
      'QR-NTW-10',
      'QR-NTW-03',
      'QR-NTW-08'
    ],
    qualitySubRiskUniqueIdArray: [],
    FunctionName: 'Member Firm Leadership',
    FunctionOwnerTitleId: [ ObjectId('6855d87771835f94ed69e686') ],
    RejectedQualityRiskUniqueIds: '',
    RejectedSubQualityRiskUniqueIds: null,
    EventAction: 'Update',
    EventDate: '2026-03-25T05:32:54.284Z',
    EventType: 'Updated',
    LastPublishedRecordStatus: 'Active'
  }
]