// db.archerentities.find({MemberFirmId:10307})
[
  {
    _id: ObjectId('69a5562107a4feb37e6d2c7a'),
    Type: 'Member Firm',
    EYNetworkUniqueId: '',
    EYNetwork: '',
    EYAreaUniqueId: '',
    EYArea: '',
    EYBusinessUnitUniqueId: '',
    EYBusinessUnit: '',
    EYClusterUniqueId: '',
    EYCluster: '',
    EYSubClusterUniqueId: '',
    EYSubCluster: '',
    EYRegionUniqueId: '',
    EYRegion: '',
    GroupRegionUniqueId: '',
    GroupRegion: '',
    GroupNetworkUniqueId: 'NTW',
    GroupNetwork: 'NETWORK',
    GroupAreaUniqueId: 'ARAr',
    GroupArea: 'AR_Area',
    GroupBusinessUnitUniqueId: 'ARReg',
    GroupBusinessUnit: 'AR_Region',
    GroupClusterUniqueId: 'ARClu',
    GroupCluster: 'AR_Cluster',
    GroupSubClusterUniqueId: 'ARScl',
    GroupSubCluster: 'AR_SCluster',
    Name: 'Surya_MF2',
    Archived: 'No',
    IsPartOfGroup: 'Yes',
    GroupName: 'AR1_Loca',
    GcdId: '',
    FirmUniqueId: ObjectId('6960bdd28b0334babd25fc04'),
    Abbreviation: null,
    FirmPublishedDate: '',
    FirstFirmPublishedDate: '',
    Location: 'Afghanistan',
    UltimateResponsibilityQCTitle: '',
    UltimateResponsibilityQCassignments: '',
    UltimateResponsibilityQCassignmentsName: '',
    OperationalResponsiblityQCTitle: '',
    OperationalResponsiblityQCassignments: '',
    OperationalResponsiblityQCassignmentsName: '',
    OperationalResponsibilityComplianceWithRequirementQCTitle: '',
    OperationalResponsibilityComplianceWithRequirementQCAssignments: '',
    OperationalResponsibilityComplianceWithRequirementQCAssignmentsName: '',
    OperationalResponsibilityMonitoringAndRemediationQCTitle: '',
    OperationalResponsibilityMonitoringAndRemediationQCAssignments: '',
    OperationalResponsibilityMonitoringAndRemediationQCAssignmentsName: '',
    IndividualoperationalresponsibilityQCTitle: '',
    IndividualoperationalresponsibilityQCassignments: '',
    IndividualoperationalresponsibilityQCassignmentsName: '',
    UltimateResponsibilitySqmTitle: '08y0jkuS; 07988974A&*; 09385520A&*',
    UltimateResponsibilitySqmAssignments: 'Satya.Akella@gds.ey.com; Surya@gds.ey.com; Sukhada.Kamtikar@ey.com; Sanju.Baloji@sg.ey.com',
    OperationalResponsibilitySqmTitle: '0OpnMPuD; 0FFXSrFr',
    OperationalResponsibilitySqmAssignments: 'Rachit.Agarwal@in.ey.com',
    OperationalResponsibilityComplianceWithRequirementTitle: '',
    OperationalResponsibilityComplianceWithRequirementAssignments: '',
    OperationalResponsibilityMonitoringAndRemediationTitle: '',
    OperationalResponsibilityMonitoringAndRemediationAssignments: '',
    UltimateResponsibilitySqmAssignmentsName: 'Satya S Kumar Akella: Satya.Akella@gds.ey.com; Surya .: Surya@gds.ey.com; Sukhada Kamtikar: Sukhada.Kamtikar@ey.com; Sanju Baloji: Sanju.Baloji@sg.ey.com',
    OperationalResponsibilitySqmAssignmentsName: 'Rachit Agarwal: Rachit.Agarwal@in.ey.com',
    OperationalResponsibilityComplianceWithRequirementAssignmentsName: '',
    OperationalResponsibilityMonitoringAndRemediationAssignmentsName: '',
    IndividualOperationalResponsibilityQCGovernanceAndLeadershipTitle: '',
    IndividualOperationalResponsibilityQCGovernanceAndLeadershipAssignments: '',
    IndividualOperationalResponsibilityQCGovernanceAndLeadershipAssignmentsName: '',
    IndividualOperationalResponsibilityQCAcceptanceAndContinuanceOfEngagementsTitle: '',
    IndividualOperationalResponsibilityQCAcceptanceAndContinuanceOfEngagementsAssignments: '',
    IndividualOperationalResponsibilityQCAcceptanceAndContinuanceOfEngagementsAssignmentsName: '',
    IndividualOperationalResponsibilityQCEngagementPerformanceTitle: '',
    IndividualOperationalResponsibilityQCEngagementPerformanceAssignments: '',
    IndividualOperationalResponsibilityQCEngagementPerformanceAssignmentsName: '',
    IndividualOperationalResponsibilityQCResourcesTitle: '',
    IndividualOperationalResponsibilityQCResourcesAssignments: '',
    IndividualOperationalResponsibilityQCResourcesAssignmentsName: '',
    IndividualOperationalResponsibilityQCInformationAndCommunicationTitle: '',
    IndividualOperationalResponsibilityQCInformationAndCommunicationAssignments: '',
    IndividualOperationalResponsibilityQCInformationAndCommunicationAssignmentsName: '',
    FirmGroupId: 'ARLO9',
    UltimateResponsibilityTitleId: [
      ObjectId('68e9a393532b8804b93b9b94'),
      ObjectId('69044a794d636931b9cecba6'),
      ObjectId('690d7e8e263784bcec4ce460')
    ],
    OperationalResponsibilitySqmTitleId: [
      ObjectId('68e9605d4d636931b9cea3fd'),
      ObjectId('693077a9263784bcec4d0b9e')
    ],
    OrIndependenceRequirementTitleId: '',
    OrMonitoringRemediationTitleId: '',
    ultimateResponsibility: [
      {
        _id: ObjectId('68e9a393532b8804b93b9b94'),
        name: '08y0jkuS',
        global: true,
        firmId: '',
        geographyId: '//',
        fiscalYear: 2026,
        isReadOnly: false,
        modifiedBy: 'p.sdt.13@gds.ey.com',
        modifiedOn: '2025-10-11T00:23:47.839Z',
        createdOn: '2025-10-11T00:23:47.839Z',
        createdBy: 'p.sdt.13@gds.ey.com'
      },
      {
        _id: ObjectId('69044a794d636931b9cecba6'),
        name: '07988974A&*',
        global: true,
        firmId: '',
        geographyId: '//',
        fiscalYear: 2026,
        isReadOnly: false,
        modifiedBy: 'p.sdt.13@gds.ey.com',
        modifiedOn: '2025-10-31T05:34:49.794Z',
        createdOn: '2025-10-31T05:34:49.794Z',
        createdBy: 'p.sdt.13@gds.ey.com',
        titleAssignments: {
          _id: ObjectId('69a5558c3d245d2628ec1009'),
          titleId: '69044a794d636931b9cecba6',
          firmId: 'ARLO9',
          geographyId: '/ARLO9/',
          assignments: [
            {
              displayName: 'Satya S Kumar Akella',
              givenName: 'Satya Kumar Akella',
              email: 'Satya.Akella@gds.ey.com',
              physicalDeliveryOfficeName: '',
              upn: 'satya.akella@gds.ey.com',
              gpn: 'IN010M51970',
              rank: 'Manager',
              location: 'India',
              firmId: '',
              geographyId: '//'
            },
            {
              displayName: 'Surya .',
              givenName: 'Surya .',
              email: 'Surya@gds.ey.com',
              physicalDeliveryOfficeName: '',
              upn: 'surya@gds.ey.com',
              gpn: '20230274515',
              rank: 'Staff/Assistant',
              location: 'India',
              firmId: 'ARLO9',
              geographyId: '//'
            }
          ],
          isDeactivated: false,
          fiscalYear: 2026,
          isReadOnly: false,
          modifiedBy: 'satya.suryaprakash.dudala@ey.com',
          modifiedOn: '2026-03-02T09:17:00.580Z',
          createdOn: '2026-03-02T09:17:00.580Z',
          createdBy: 'satya.suryaprakash.dudala@ey.com'
        }
      },
      {
        _id: ObjectId('690d7e8e263784bcec4ce460'),
        name: '09385520A&*',
        global: true,
        firmId: '',
        geographyId: '//',
        fiscalYear: 2026,
        isReadOnly: false,
        modifiedBy: 'p.sdt.13@gds.ey.com',
        modifiedOn: '2025-11-07T05:07:26.869Z',
        createdOn: '2025-11-07T05:07:26.869Z',
        createdBy: 'p.sdt.13@gds.ey.com',
        titleAssignments: {
          _id: ObjectId('69a555a73d245d2628ec100d'),
          titleId: '690d7e8e263784bcec4ce460',
          firmId: 'ARLO9',
          geographyId: '/ARLO9/',
          assignments: [
            {
              displayName: 'Sukhada Kamtikar',
              givenName: 'Sukhada Kamtikar',
              email: 'Sukhada.Kamtikar@ey.com',
              physicalDeliveryOfficeName: '',
              upn: 'sukhada.kamtikar@ey.com',
              gpn: 'US015985791',
              rank: 'Administrative Contractor',
              location: 'India',
              firmId: '',
              geographyId: '//'
            },
            {
              displayName: 'Sanju Baloji',
              givenName: 'Sanju Baloji',
              email: 'Sanju.Baloji@sg.ey.com',
              physicalDeliveryOfficeName: '',
              upn: 'sanju.baloji@sg.ey.com',
              gpn: '20230018826',
              rank: 'Manager',
              location: 'Singapore',
              firmId: 'ARLO9',
              geographyId: '//'
            }
          ],
          isDeactivated: false,
          fiscalYear: 2026,
          isReadOnly: false,
          modifiedBy: 'satya.suryaprakash.dudala@ey.com',
          modifiedOn: '2026-03-02T09:17:27.296Z',
          createdOn: '2026-03-02T09:17:27.296Z',
          createdBy: 'satya.suryaprakash.dudala@ey.com'
        }
      }
    ],
    operationalResponsibilitySqm: [
      {
        _id: ObjectId('68e9605d4d636931b9cea3fd'),
        name: '0OpnMPuD',
        global: true,
        firmId: '',
        geographyId: '//',
        fiscalYear: 2026,
        isReadOnly: false,
        modifiedBy: 'p.sdt.13@gds.ey.com',
        modifiedOn: '2025-10-10T19:37:00.881Z',
        createdOn: '2025-10-10T19:37:00.881Z',
        createdBy: 'p.sdt.13@gds.ey.com',
        titleAssignments: {
          _id: ObjectId('69a555953d245d2628ec100b'),
          titleId: '68e9605d4d636931b9cea3fd',
          firmId: 'ARLO9',
          geographyId: '/ARLO9/',
          assignments: [
            {
              displayName: 'Rachit Agarwal',
              givenName: 'Rachit Agarwal',
              email: 'Rachit.Agarwal@in.ey.com',
              physicalDeliveryOfficeName: '',
              upn: 'rachit.agarwal@in.ey.com',
              gpn: 'IN010K13233',
              rank: 'Senior Manager',
              location: 'India',
              firmId: '',
              geographyId: '//'
            }
          ],
          isDeactivated: false,
          fiscalYear: 2026,
          isReadOnly: false,
          modifiedBy: 'satya.suryaprakash.dudala@ey.com',
          modifiedOn: '2026-03-02T09:17:09.222Z',
          createdOn: '2026-03-02T09:17:09.222Z',
          createdBy: 'satya.suryaprakash.dudala@ey.com'
        }
      },
      {
        _id: ObjectId('693077a9263784bcec4d0b9e'),
        name: '0FFXSrFr',
        global: true,
        firmId: '',
        geographyId: '//',
        fiscalYear: 2026,
        isReadOnly: false,
        modifiedBy: 'p.sdt.13@gds.ey.com',
        modifiedOn: '2025-12-03T17:47:21.209Z',
        createdOn: '2025-12-03T17:47:21.209Z',
        createdBy: 'p.sdt.13@gds.ey.com'
      }
    ],
    MemberFirmId: 10307,
    ArcherPublishedOn: '2026-03-02T09:18:39.023Z',
    Rollforwarded: 'No',
    Published: 'No',
    RollforwardedDate: '',
    ArchivedDate: '',
    PCAOBEnabled: 'Yes',
    EntityFiscalYear: 2026,
    SQMLeadership: 'Satya.Akella@gds.ey.com; Surya@gds.ey.com; Sukhada.Kamtikar@ey.com; Sanju.Baloji@sg.ey.com;Rachit.Agarwal@in.ey.com',
    SQMPCAOBLeadership: '',
    FiscalYear: 'FY26'
  }
]