isqc> db.rebacpolicy.find()
[
  {
    _id: ObjectId('69ca9a68cd52d346ca8ce5b1'),
    policyId: 'EXC-GLOBAL-LOC-GLOBAL-USA',
    fiscalYear: 2026,
    fromType: 'EntityType_Area',
    fromEntity: 'AME',
    fromGeography: '/AME/',
    toType: 'Location',
    toEntity: 'USA',
    toGeography: '/USA/',
    objectId: 'QO-AME-13',
    objectType: [ 'QualityObjective' ],
    active: true,
    reason: 'Quality Objective QO-AME-13 marked as Not Applicable for USA',
    modifiedBy: 'Script_for_Global_QO_Applicability_Update_at_USA',
    modifiedOn: '2026-03-30T15:44:40.581Z',
    createdBy: 'Script_for_Global_QO_Applicability_Update_at_USA',
    createdOn: '2026-03-30T15:44:40.581Z'
  },
  {
    _id: ObjectId('69ca9a68cd52d346ca8ce5b0'),
    policyId: 'EXC-GLOBAL-LOC-GLOBAL-USA',
    fiscalYear: 2026,
    fromType: 'EntityType_Network',
    fromEntity: 'NTW',
    fromGeography: '/NTW/',
    toType: 'Location',
    toEntity: 'USA',
    toGeography: '/USA/',
    objectId: 'QO-NTW-137',
    objectType: [ 'QualityObjective' ],
    active: true,
    reason: 'Quality Objective QO-NTW-137 marked as Not Applicable for USA',
    modifiedBy: 'Script_for_Global_QO_Applicability_Update_at_USA',
    modifiedOn: '2026-03-30T15:44:40.225Z',
    createdBy: 'Script_for_Global_QO_Applicability_Update_at_USA',
    createdOn: '2026-03-30T15:44:40.225Z'
  },
  {
    _id: ObjectId('69ca9a68cd52d346ca8ce5b2'),
    policyId: 'EXC-GLOBAL-LOC-GLOBAL-USA',
    fiscalYear: 2026,
    fromType: 'EntityType_Region',
    fromEntity: 'USLI',
    fromGeography: '/USLI/',
    toType: 'Location',
    toEntity: 'USA',
    toGeography: '/USA/',
    objectId: 'QO-USLI-02',
    objectType: [ 'QualityObjective' ],
    active: true,
    reason: 'Quality Objective QO-USLI-02 marked as Not Applicable for USA',
    modifiedBy: 'Script_for_Global_QO_Applicability_Update_at_USA',
    modifiedOn: '2026-03-30T15:44:40.863Z',
    createdBy: 'Script_for_Global_QO_Applicability_Update_at_USA',
    createdOn: '2026-03-30T15:44:40.863Z'
  },
  {
    _id: ObjectId('69cbb0e7b294bd84f18ce5b0'),
    policyId: 'EXC-GLOBAL-LOC-GLOBAL-USA',
    fiscalYear: 2026,
    fromType: 'EntityType_Network',
    fromEntity: 'NTW',
    fromGeography: '/NTW/',
    toType: 'Location',
    toEntity: 'USA',
    toGeography: '/USA/',
    objectId: 'QO-NTW-138',
    objectType: [ 'QualityObjective' ],
    active: true,
    reason: 'Quality Objective QO-NTW-138 marked as Not Applicable for USA',
    modifiedBy: 'Script_for_Global_QO_Applicability_Update_at_USA',
    modifiedOn: '2026-03-31T11:32:53.369Z',
    createdBy: 'Script_for_Global_QO_Applicability_Update_at_USA',
    createdOn: '2026-03-31T11:32:53.369Z'
  },
  {
    _id: ObjectId('69cbb0e7b294bd84f18ce5b3'),
    policyId: 'EXC-GLOBAL-LOC-GLOBAL-USA',
    fiscalYear: 2026,
    fromType: 'EntityType_Network',
    fromEntity: 'NTW',
    fromGeography: '/NTW/',
    toType: 'Location',
    toEntity: 'USA',
    toGeography: '/USA/',
    objectId: 'QO-NTW-143',
    objectType: [ 'QualityObjective' ],
    active: true,
    reason: 'Quality Objective QO-NTW-143 marked as Not Applicable for USA',
    modifiedBy: 'Script_for_Global_QO_Applicability_Update_at_USA',
    modifiedOn: '2026-03-31T11:32:54.106Z',
    createdBy: 'Script_for_Global_QO_Applicability_Update_at_USA',
    createdOn: '2026-03-31T11:32:54.106Z'
  },
  {
    _id: ObjectId('69cbb0e7b294bd84f18ce5b2'),
    policyId: 'EXC-GLOBAL-LOC-GLOBAL-USA',
    fiscalYear: 2026,
    fromType: 'EntityType_Network',
    fromEntity: 'NTW',
    fromGeography: '/NTW/',
    toType: 'Location',
    toEntity: 'USA',
    toGeography: '/USA/',
    objectId: 'QO-NTW-140',
    objectType: [ 'QualityObjective' ],
    active: true,
    reason: 'Quality Objective QO-NTW-140 marked as Not Applicable for USA',
    modifiedBy: 'Script_for_Global_QO_Applicability_Update_at_USA',
    modifiedOn: '2026-03-31T11:32:53.878Z',
    createdBy: 'Script_for_Global_QO_Applicability_Update_at_USA',
    createdOn: '2026-03-31T11:32:53.878Z'
  },
  {
    _id: ObjectId('69cbb0e7b294bd84f18ce5b1'),
    policyId: 'EXC-GLOBAL-LOC-GLOBAL-USA',
    fiscalYear: 2026,
    fromType: 'EntityType_Network',
    fromEntity: 'NTW',
    fromGeography: '/NTW/',
    toType: 'Location',
    toEntity: 'USA',
    toGeography: '/USA/',
    objectId: 'QO-NTW-139',
    objectType: [ 'QualityObjective' ],
    active: true,
    reason: 'Quality Objective QO-NTW-139 marked as Not Applicable for USA',
    modifiedBy: 'Script_for_Global_QO_Applicability_Update_at_USA',
    modifiedOn: '2026-03-31T11:32:53.617Z',
    createdBy: 'Script_for_Global_QO_Applicability_Update_at_USA',
    createdOn: '2026-03-31T11:32:53.617Z'
  },
  {
    _id: ObjectId('69cbb0e7b294bd84f18ce5b6'),
    policyId: 'EXC-GLOBAL-LOC-GLOBAL-USA',
    fiscalYear: 2026,
    fromType: 'EntityType_Network',
    fromEntity: 'NTW',
    fromGeography: '/NTW/',
    toType: 'Location',
    toEntity: 'USA',
    toGeography: '/USA/',
    objectId: 'QO-NTW-148',
    objectType: [ 'QualityObjective' ],
    active: true,
    reason: 'Quality Objective QO-NTW-148 marked as Not Applicable for USA',
    modifiedBy: 'Script_for_Global_QO_Applicability_Update_at_USA',
    modifiedOn: '2026-03-31T11:32:54.833Z',
    createdBy: 'Script_for_Global_QO_Applicability_Update_at_USA',
    createdOn: '2026-03-31T11:32:54.833Z'
  },
  {
    _id: ObjectId('69cbb0e7b294bd84f18ce5b4'),
    policyId: 'EXC-GLOBAL-LOC-GLOBAL-USA',
    fiscalYear: 2026,
    fromType: 'EntityType_Network',
    fromEntity: 'NTW',
    fromGeography: '/NTW/',
    toType: 'Location',
    toEntity: 'USA',
    toGeography: '/USA/',
    objectId: 'QO-NTW-144',
    objectType: [ 'QualityObjective' ],
    active: true,
    reason: 'Quality Objective QO-NTW-144 marked as Not Applicable for USA',
    modifiedBy: 'Script_for_Global_QO_Applicability_Update_at_USA',
    modifiedOn: '2026-03-31T11:32:54.361Z',
    createdBy: 'Script_for_Global_QO_Applicability_Update_at_USA',
    createdOn: '2026-03-31T11:32:54.361Z'
  },
  {
    _id: ObjectId('69cbb0e7b294bd84f18ce5b5'),
    policyId: 'EXC-GLOBAL-LOC-GLOBAL-USA',
    fiscalYear: 2026,
    fromType: 'EntityType_Network',
    fromEntity: 'NTW',
    fromGeography: '/NTW/',
    toType: 'Location',
    toEntity: 'USA',
    toGeography: '/USA/',
    objectId: 'QO-NTW-145',
    objectType: [ 'QualityObjective' ],
    active: true,
    reason: 'Quality Objective QO-NTW-145 marked as Not Applicable for USA',
    modifiedBy: 'Script_for_Global_QO_Applicability_Update_at_USA',
    modifiedOn: '2026-03-31T11:32:54.599Z',
    createdBy: 'Script_for_Global_QO_Applicability_Update_at_USA',
    createdOn: '2026-03-31T11:32:54.599Z'
  },
  {
    _id: ObjectId('69cbb0e7b294bd84f18ce5b7'),
    policyId: 'EXC-GLOBAL-LOC-GLOBAL-USA',
    fiscalYear: 2026,
    fromType: 'EntityType_Network',
    fromEntity: 'NTW',
    fromGeography: '/NTW/',
    toType: 'Location',
    toEntity: 'USA',
    toGeography: '/USA/',
    objectId: 'QO-NTW-149',
    objectType: [ 'QualityObjective' ],
    active: true,
    reason: 'Quality Objective QO-NTW-149 marked as Not Applicable for USA',
    modifiedBy: 'Script_for_Global_QO_Applicability_Update_at_USA',
    modifiedOn: '2026-03-31T11:32:55.076Z',
    createdBy: 'Script_for_Global_QO_Applicability_Update_at_USA',
    createdOn: '2026-03-31T11:32:55.076Z'
  }
]