// isqcuat> db.sqmarcherkeycontrol.find({UniqueControlID:'AME-RC-NTW-412',FiscalYear: 'FY26'})
[
  {
    _id: ObjectId('69e7426b0aae8818d7ebb66d'),
    ActiveQualityRiskUniqueIds: 'QR-NTW-87',
    ActiveQualitySubRiskUniqueIds: '',
    AdditionalQOs: [],
    AdditionalQRs: [],
    ArcherPublishedOn: '2026-04-21T09:24:47.269Z',
    AreaId: 'AME',
    BusinessUnitId: '',
    ClusterId: '',
    ControlCriteria: ' The archive notification rules are reviewed and approved to ensure that they are configured in line with the applicable requirements.',
    ControlCriteriaLocal: '',
    ControlDescription: 'Annually, rules set up in ARC for automated notifications are reviewed and validated against the appropriate requirements.\n' +
      '\n' +
      'If differences are identified, then actions are taken to update those notifications that may have an incorrect rule set for them.',
    ControlDescriptionLocal: '',
    ControlDesignedByName: 'NETWORK',
    ControlDesignedByType: 'Network',
    ControlName: 'Annual review and verification of ARC Notification Management configuration',
    ControlNameLocal: '',
    ControlNature: 'Detect',
    ControlObjective: ' To evaluate if the archive notification rules in ARC match the applicable requirements.',
    ControlObjectiveLocal: '',
    ControlOperatorTitleAssignments: '',
    ControlOperatorTitleIDs: '',
    ControlOperatorTitles: '',
    ControlOwnerProceduresOverCompleteness: 'IEC-ID-232915:',
    ControlOwnerProceduresOverCompletenessLocal: '',
    ControlOwnerTitleAssignments: '',
    ControlOwnerTitles: 'Region ARC Coordinator',
    ControlOwnerTitlesIDs: '6855d87f71835f94ed69e8db',
    ControlType: 'IT Dependent Manual',
    ControlsByPeriod: 'Control added in FY26',
    Draft: false,
    EngagementType: '',
    EntityFiscalYear: 2026,
    EntityId: 'AME',
    EntityType: 'Area',
    ExecutingEntity: 'Americas',
    FirmPublishedDate: '2026-04-20T15:07:56.671Z',
    FiscalYear: 'FY26',
    Frequency: 'Annually',
    FunctionBaselineControlDesign: '6855d87271835f94ed69e550',
    FunctionBaselineControlExecution: '6855d87171835f94ed69e528',
    FunctionBaselineLocalControlDesign: '6855d87471835f94ed69e5ca',
    FunctionId: '6855d87171835f94ed69e528',
    FunctionOwnerAssignments: '',
    FunctionOwnerTitle: '',
    IEC: 'IEC-ID-232915:ARC Notification Centre',
    IECIDs: '232915',
    IECLocal: null,
    IECRationale: 'TBD',
    IECRationaleLocal: '',
    IECReportType: 'IEC-ID-232915:Modifiable',
    IECSystems: 'IEC-ID-232915:TECH-NTW-IS: ARC (Archive Records Center)',
    IsControlOverResource: true,
    IsControlOverResourceNew: 'Yes',
    IsQoOverrideEnabled: '',
    IsThisIECReportOrOther: 'IEC-ID-232915:Other',
    KeyControlOperatedByServiceProvider: false,
    KeyControlOperatedByServiceProviderNew: 'No',
    LastProcessedDate: '2026-04-21T09:24:47.269Z',
    LocalLanguage: '',
    MemberFirmId: '',
    NetworkId: '',
    PCAOB_Configured_Object: 'No',
    PerformedOnBehalfOf: 'United States of America; Uruguay; Colombia; Chile; Aruba; Panama; Venezuela; Paraguay; Costa Rica; Ecuador; Mexico; Jamaica; Bermuda; Peru; Israel; Cayman Islands; El Salvador; Curacao; Trinidad and Tobago; Honduras; Bolivia; Dominican Republic; Guatemala; Argentina; Barbados; Brazil; Suriname; Bahamas; St. Lucia; Nicaragua; Guyana',
    ProcessId: [ ObjectId('6855d87171835f94ed69e50f') ],
    ProcessUniqueId: 'PR-06',
    QualityObjectiveUniquesIds: '',
    Ref_UniqueId: 'RC-NTW-412',
    RegionId: '',
    RelatedPolicyProcedureManualGuidance: ' TBD',
    RelatedPolicyProcedureManualGuidanceLocal: '',
    ResourceIds: '6855d8d871835f94ed69edbe',
    ResourceName: 'TECH-NTW-IS: ARC (Archive Records Center)',
    ResourceType: 'Technology',
    ServiceLine: '',
    ServiceProviderName: '',
    ServiceProviderNameLocal: '',
    SubClusterId: '',
    SupportingEvidence: '1. Confirmation of review, any changes as a result of the review and relevant requirements; 2. Screenshots showing notification setting is turned "on" and is set to "archive due in 7, 15 or 30 days"',
    SupportingEvidenceLocal: '',
    SupportingITApplication: 'TECH-NTW-IS: ARC (Archive Records Center)',
    Tags: '',
    UniqueControlID: 'AME-RC-NTW-412',
    qualityObjectiveUniqueIdArray: [ 'QO-NTW-33' ],
    qualityRiskUniqueIdArray: [ 'QR-NTW-87' ],
    qualitySubRiskUniqueIdArray: [],
    FunctionName: '',
    FunctionOwnerTitleId: [],
    RejectedQualityRiskUniqueIds: '',
    RejectedSubQualityRiskUniqueIds: null,
    EventAction: 'Update',
    EventDate: '2026-03-27T11:02:54.492Z',
    EventType: 'New',
    LastPublishedRecordStatus: 'Active'
  }
]