isqc> db.sqmarcherkeycontrol.find({UniqueControlID:'USA-RC-NTW-452'}).pretty()
[
  {
    _id: ObjectId('69cb1ff0bb44c31014180a27'),
    ActiveQualityRiskUniqueIds: 'QR-NTW-300',
    ActiveQualitySubRiskUniqueIds: 'SR-NTW-16',
    AdditionalQOs: [],
    AdditionalQRs: [],
    ArcherPublishedOn: '2026-03-31T01:13:25.480Z',
    AreaId: '',
    BusinessUnitId: '',
    ClusterId: '',
    ControlCriteria: ' Archer-BKC-03',
    ControlCriteriaLocal: '',
    ControlDescription: 'Archer-BKC-03',
    ControlDescriptionLocal: '',
    ControlDesignedByName: 'NETWORK',
    ControlDesignedByType: 'Network',
    ControlName: 'Archer-BKC-03',
    ControlNameLocal: '',
    ControlNature: 'Detect',
    ControlObjective: ' Archer-BKC-03',
    ControlObjectiveLocal: '',
    ControlOperatorTitleAssignments: 'Maregouni.Priyanka@gds.ey.com',
    ControlOperatorTitleIDs: '6855d87a71835f94ed69e76a;68c9c15218a25cd375fa34cd',
    ControlOperatorTitles: 'Global QEL - PWT Administrator;Data & Intelligence Delivery (DID) Team Support',
    ControlOwnerProceduresOverCompleteness: 'IEC-ID-1130877:Archer-BKC-03',
    ControlOwnerProceduresOverCompletenessLocal: '',
    ControlOwnerTitleAssignments: 'michele.austin@ey.com',
    ControlOwnerTitles: 'Global Tool - Retain Technology Owner (1);Country Independence Access Coordinator - BRIDGE',
    ControlOwnerTitlesIDs: '6855d87f71835f94ed69e914;68c9c15118a25cd375fa3419',
    ControlType: 'IT Dependent Manual',
    ControlsByPeriod: 'Control added in FY26',
    Draft: false,
    EngagementType: 'Other Assurance;Reviews of financial statements;Compilation;Audit of financial statements;Agreed upon procedures',
    EntityFiscalYear: 2026,
    EntityId: 'USA',
    EntityType: 'Location',
    EventAction: 'Update',
    EventDate: '2026-03-31T07:39:08.429Z',
    EventType: 'Rejected',
    ExecutingEntity: 'United States of America',
    FirmPublishedDate: '2026-04-01T10:24:48.360Z',
    FiscalYear: 'FY26',
    Frequency: 'Annually;Semi-Annual',
    FunctionBaselineControlDesign: '6855d87571835f94ed69e5f9',
    FunctionBaselineControlExecution: '6855d87071835f94ed69e4e4',
    FunctionBaselineLocalControlDesign: '6855d87471835f94ed69e5aa',
    FunctionId: '6855d87071835f94ed69e4e4',
    FunctionName: 'Amer/US-Assurance Talent',
    FunctionOwnerAssignments: 'Diana.Kutz@ey.com',
    FunctionOwnerTitle: 'Americas Assurance Talent Leader',
    FunctionOwnerTitleId: [ ObjectId('68c9c15018a25cd375fa337e') ],
    IEC: 'IEC-ID-1130877:Archer-BKC-03',
    IECIDs: '1130877',
    IECLocal: null,
    IECRationale: 'Archer-BKC-03',
    IECRationaleLocal: '',
    IECReportType: 'IEC-ID-1130877:Non-modifiable',
    IECSystems: 'IEC-ID-1130877:QMT (Quality Monitoring Tool) (Assurance);IEC-ID-1130877:EY Canvas',
    IsControlOverResource: false,
    IsControlOverResourceNew: 'No',
    IsQoOverrideEnabled: '',
    IsThisIECReportOrOther: 'IEC-ID-1130877:Report (Fundamental & Significant)',
    KeyControlOperatedByServiceProvider: false,
    KeyControlOperatedByServiceProviderNew: 'No',
    LastProcessedDate: '2026-04-01T11:00:23.385Z',
    LastPublishedRecordStatus: 'Inactive',
    LocalLanguage: '',
    MemberFirmId: 'USA',
    NetworkId: '',
    PCAOB_Configured_Object: 'Yes',
    PerformedOnBehalfOf: 'United States of America',
    ProcessId: [ ObjectId('6855d86f71835f94ed69e4bc') ],
    ProcessUniqueId: 'PR-39',
    QualityObjectiveUniquesIds: 'QO_03',
    Ref_UniqueId: 'RC-NTW-452',
    RegionId: '',
    RejectedQualityRiskUniqueIds: '',
    RejectedSubQualityRiskUniqueIds: '',
    RelatedPolicyProcedureManualGuidance: ' Archer-BKC-03',
    RelatedPolicyProcedureManualGuidanceLocal: '',
    ResourceIds: '',
    ResourceName: '',
    ResourceType: '',
    ServiceLine: 'CBS; Assurance; Tax; Consulting; Strategy and Transactions; GDS',
    ServiceProviderName: '',
    ServiceProviderNameLocal: '',
    SubClusterId: '',
    SupportingEvidence: 'Archer-BKC-03',
    SupportingEvidenceLocal: '',
    SupportingITApplication: 'QMT (Quality Monitoring Tool) (Assurance); EY Canvas',
    Tags: 'Annual Confirmation;All ISQM1 in scope engagements including SIRs',
    UniqueControlID: 'USA-RC-NTW-452',
    qualityObjectiveUniqueIdArray: [ 'QO-NTW-139' ],
    qualityRiskUniqueIdArray: [ 'QR-NTW-300' ],
    qualitySubRiskUniqueIdArray: [ 'SR-NTW-16' ]
  }
]