// isqcuat> db.sqmarcherkeycontrol.find({UniqueControlID:'AME-RC-NTW-412',FiscalYear: 'FY26'})
[
  {
    _id: ObjectId('69e7426b0aae8818d7ebb66d'),
    ActiveQualityRiskUniqueIds: 'QR-NTW-87',
    ActiveQualitySubRiskUniqueIds: '',
    AdditionalQOs: [],
    AdditionalQRs: [],
    ArcherPublishedOn: '2026-04-21T09:24:47.269Z',
    AreaId: 'AME',
    BusinessUnitId: '',
    ClusterId: '',
    ControlCriteria: ' The archive notification rules are reviewed and approved to ensure that they are configured in line with the applicable requirements.',
    ControlCriteriaLocal: '',
    ControlDescription: 'Annually, rules set up in ARC for automated notifications are reviewed and validated against the appropriate requirements.\n' +
      '\n' +
      'If differences are identified, then actions are taken to update those notifications that may have an incorrect rule set for them.',
    ControlDescriptionLocal: '',
    ControlDesignedByName: 'NETWORK',
    ControlDesignedByType: 'Network',
    ControlName: 'Annual review and verification of ARC Notification Management configuration',
    ControlNameLocal: '',
    ControlNature: 'Detect',
    ControlObjective: ' To evaluate if the archive notification rules in ARC match the applicable requirements.',
    ControlObjectiveLocal: '',
    ControlOperatorTitleAssignments: '',
    ControlOperatorTitleIDs: '',
    ControlOperatorTitles: '',
    ControlOwnerProceduresOverCompleteness: 'IEC-ID-232915:',
    ControlOwnerProceduresOverCompletenessLocal: '',
    ControlOwnerTitleAssignments: '',
    ControlOwnerTitles: 'Region ARC Coordinator',
    ControlOwnerTitlesIDs: '6855d87f71835f94ed69e8db',
    ControlType: 'IT Dependent Manual',
    ControlsByPeriod: 'Control added in FY26',
    Draft: false,
    EngagementType: '',
    EntityFiscalYear: 2026,
    EntityId: 'AME',
    EntityType: 'Area',
    ExecutingEntity: 'Americas',
    FirmPublishedDate: '2026-04-20T15:07:56.671Z',
    FiscalYear: 'FY26',
    Frequency: 'Annually',
    FunctionBaselineControlDesign: '6855d87271835f94ed69e550',
    FunctionBaselineControlExecution: '6855d87171835f94ed69e528',
    FunctionBaselineLocalControlDesign: '6855d87471835f94ed69e5ca',
    FunctionId: '6855d87171835f94ed69e528',
    FunctionOwnerAssignments: '',
    FunctionOwnerTitle: '',
    IEC: 'IEC-ID-232915:ARC Notification Centre',
    IECIDs: '232915',
    IECLocal: null,
    IECRationale: 'TBD',
    IECRationaleLocal: '',
    IECReportType: 'IEC-ID-232915:Modifiable',
    IECSystems: 'IEC-ID-232915:TECH-NTW-IS: ARC (Archive Records Center)',
    IsControlOverResource: true,
    IsControlOverResourceNew: 'Yes',
    IsQoOverrideEnabled: '',
    IsThisIECReportOrOther: 'IEC-ID-232915:Other',
    KeyControlOperatedByServiceProvider: false,
    KeyControlOperatedByServiceProviderNew: 'No',
    LastProcessedDate: '2026-04-21T09:24:47.269Z',
    LocalLanguage: '',
    MemberFirmId: '',
    NetworkId: '',
    PCAOB_Configured_Object: 'No',
    PerformedOnBehalfOf: 'United States of America; Uruguay; Colombia; Chile; Aruba; Panama; Venezuela; Paraguay; Costa Rica; Ecuador; Mexico; Jamaica; Bermuda; Peru; Israel; Cayman Islands; El Salvador; Curacao; Trinidad and Tobago; Honduras; Bolivia; Dominican Republic; Guatemala; Argentina; Barbados; Brazil; Suriname; Bahamas; St. Lucia; Nicaragua; Guyana',
    ProcessId: [ ObjectId('6855d87171835f94ed69e50f') ],
    ProcessUniqueId: 'PR-06',
    QualityObjectiveUniquesIds: '',
    Ref_UniqueId: 'RC-NTW-412',
    RegionId: '',
    RelatedPolicyProcedureManualGuidance: ' TBD',
    RelatedPolicyProcedureManualGuidanceLocal: '',
    ResourceIds: '6855d8d871835f94ed69edbe',
    ResourceName: 'TECH-NTW-IS: ARC (Archive Records Center)',
    ResourceType: 'Technology',
    ServiceLine: '',
    ServiceProviderName: '',
    ServiceProviderNameLocal: '',
    SubClusterId: '',
    SupportingEvidence: '1. Confirmation of review, any changes as a result of the review and relevant requirements; 2. Screenshots showing notification setting is turned "on" and is set to "archive due in 7, 15 or 30 days"',
    SupportingEvidenceLocal: '',
    SupportingITApplication: 'TECH-NTW-IS: ARC (Archive Records Center)',
    Tags: '',
    UniqueControlID: 'AME-RC-NTW-412',
    qualityObjectiveUniqueIdArray: [ 'QO-NTW-33' ],
    qualityRiskUniqueIdArray: [ 'QR-NTW-87' ],
    qualitySubRiskUniqueIdArray: [],
    FunctionName: '',
    FunctionOwnerTitleId: [],
    RejectedQualityRiskUniqueIds: '',
    RejectedSubQualityRiskUniqueIds: null,
    EventAction: 'Update',
    EventDate: '2026-03-27T11:02:54.492Z',
    EventType: 'New',
    LastPublishedRecordStatus: 'Active'
  }
]

// isqcuat> db.sqmarcherkeycontrol.find({UniqueControlID:'EME-RC-NTW-55',FiscalYear: 'FY26'})
[
  {
    _id: ObjectId('691b74ae6292b5078f383a82'),
    ActiveQualityRiskUniqueIds: 'QR-NTW-22;QR-NTW-19;QR-NTW-17;QR-NTW-16;QR-NTW-23;QR-NTW-20;QR-NTW-128',
    ActiveQualitySubRiskUniqueIds: '',
    AdditionalQOs: [],
    AdditionalQRs: [],
    ArcherPublishedOn: '2025-11-17T19:13:55.819Z',
    AreaId: 'EME',
    BusinessUnitId: '',
    ClusterId: '',
    ControlCriteria: ' To review and affirm for Partners whether:\n' +
      '- sanctions applied by Assigned Reviewer & Regional Function Contacts are appropriate\n' +
      '- sanctions are in accordance with Global / Area Sanctions framework \n' +
      '- to evaluate and recommend additional actions if needed.\n' +
      '\n' +
      'Note: Information from confidential ethics reports, including information from Navex is not auditable without the data being anonymised, in line with local laws and regulations',
    ControlCriteriaLocal: '',
    ControlDescription: 'AEOC reviews periodically a summary report of sanctions applied to partners for ethical breaches received from Area RM Leaders/ Delegates.\n' +
      'AEOC exercises oversight to affirm that the nature of sanctions applied to Partners is appropriate and recommends additional actions if needed.\n',
    ControlDescriptionLocal: '',
    ControlDesignedByName: 'NETWORK',
    ControlDesignedByType: 'Network',
    ControlName: 'Review and affirm a summary of ethics reports periodically to ratify or challenge the nature, consistency and appropriateness of the sanctions applied.',
    ControlNameLocal: '',
    ControlNature: 'Detect',
    ControlObjective: ' To affirm the nature of sanctions applied is appropriate and in accordance with Sanctions framework and to recommend additional actions if needed.\n',
    ControlObjectiveLocal: '',
    ControlOperatorTitleAssignments: '',
    ControlOperatorTitleIDs: '',
    ControlOperatorTitles: '',
    ControlOwnerProceduresOverCompleteness: '',
    ControlOwnerProceduresOverCompletenessLocal: '',
    ControlOwnerTitleAssignments: 'Jonathan.Blackmore@uk.ey.com',
    ControlOwnerTitles: 'Area Ethics Oversight Committee Chair',
    ControlOwnerTitlesIDs: '6855d87871835f94ed69e6c8',
    ControlType: 'Manual',
    ControlsByPeriod: 'Rolled forward Control',
    Draft: false,
    EngagementType: 'Compilation;Reviews of financial statements;Agreed upon procedures;Audit of financial statements;Other Assurance',
    EntityFiscalYear: 2026,
    EntityId: 'EME',
    EntityType: 'Area',
    ExecutingEntity: 'EMEIA',
    FirmPublishedDate: '2025-11-17T19:05:30.494Z',
    FiscalYear: 'FY26',
    Frequency: 'Annually',
    FunctionBaselineControlDesign: '6855d86f71835f94ed69e4b2',
    FunctionBaselineControlExecution: '6855d86f71835f94ed69e4b2',
    FunctionBaselineLocalControlDesign: '6855d86f71835f94ed69e4b2',
    FunctionId: '6855d86f71835f94ed69e4b2',
    FunctionOwnerAssignments: 'Jonathan.Blackmore@uk.ey.com',
    FunctionOwnerTitle: 'Area Risk Management Leader',
    IEC: 'Area Summary - Ethics Report (Sanctions Report); Minutes of AEOC’s Meeting; Global / Area Sanctions framework.',
    IECIDs: '',
    IECLocal: null,
    IECRationale: '',
    IECRationaleLocal: '',
    IECReportType: '',
    IECSystems: '',
    IsControlOverResource: false,
    IsControlOverResourceNew: 'No',
    IsQoOverrideEnabled: '',
    IsThisIECReportOrOther: '',
    KeyControlOperatedByServiceProvider: false,
    KeyControlOperatedByServiceProviderNew: 'No',
    LastProcessedDate: '2025-11-17T19:13:55.819Z',
    LocalLanguage: '',
    MemberFirmId: '',
    NetworkId: '',
    PCAOB_Configured_Object: 'No',
    PerformedOnBehalfOf: 'Denmark; Ireland; Malawi; Rwanda; Zambia; Poland; Kuwait; Finland; France; Italy; Switzerland; United Kingdom; Bahrain; Iraq; Kenya; Nigeria; Netherlands; Egypt; Lebanon; Libya; Oman; South Africa; Sweden; Saudi Arabia; Tanzania; Uganda; Isle of Man; Spain; Mauritius; Ghana; India; Luxembourg; Norway; United Arab Emirates; Jordan; Palestinian Authority; Germany; Botswana; Namibia; Qatar; Slovenia; Uzbekistan; Bangladesh; Montenegro; Moldova; Ukraine; Cote d Ivoire; Algeria; Senegal; Slovak Republic; Greece; Malta; Morocco; Pakistan; Albania; Angola; Turkey; Guinea; Kazakhstan; Kosovo; Estonia; Cameroon; Armenia; Gabon; Georgia; Hungary; Republic of Congo; Lithuania; Azerbaijan; Czech Republic; Belgium; Monaco; Latvia; Portugal; Tunisia; Liechtenstein; Kyrgyzstan; Mozambique; Cyprus; Bulgaria; Croatia; Austria; Democratic Republic of the Congo; Romania; Serbia; Macedonia; Gibraltar; Zimbabwe; Bosnia and Herzegovina; Cape Verde',
    ProcessId: [ ObjectId('6855d87271835f94ed69e540') ],
    ProcessUniqueId: 'PR-56',
    QualityObjectiveUniquesIds: 'RER Objective 3;RER Objective 2;G&L Objective 7;RER Objective 5;RER Objective 7',
    Ref_UniqueId: 'RC-NTW-55',
    RegionId: '',
    RelatedPolicyProcedureManualGuidance: ' Reporting and resolving complaints and allegations about non-compliance with EY policies and Code of Conduct, and other laws, regulations, or professional standards\n' +
      '\n' +
      'Guidance on establishing Member Firm procedures',
    RelatedPolicyProcedureManualGuidanceLocal: '',
    ResourceIds: '',
    ResourceName: '',
    ResourceType: '',
    ServiceLine: 'GDS; Tax; Strategy and Transactions; Assurance; Consulting',
    ServiceProviderName: '',
    ServiceProviderNameLocal: '',
    SubClusterId: '',
    SupportingEvidence: 'IPE Area Summary - Ethics Report (Sanctions Report); Minutes of AEOC’s Meeting',
    SupportingEvidenceLocal: '',
    SupportingITApplication: '',
    Tags: 'Specified Response : (ISQM 1.34(a));Specified Response : (ISQM 1.34(c))',
    UniqueControlID: 'EME-RC-NTW-55',
    qualityObjectiveUniqueIdArray: [ 'QO-NTW-08', 'QO-NTW-09', 'QO-NTW-37', 'QO-NTW-38', 'QO-NTW-40' ],
    qualityRiskUniqueIdArray: [
      'QR-NTW-22',
      'QR-NTW-19',
      'QR-NTW-17',
      'QR-NTW-16',
      'QR-NTW-23',
      'QR-NTW-20',
      'QR-NTW-128'
    ],
    qualitySubRiskUniqueIdArray: [],
    FunctionName: 'Risk Management',
    FunctionOwnerTitleId: [ ObjectId('6855d87671835f94ed69e651') ],
    RejectedQualityRiskUniqueIds: '',
    RejectedSubQualityRiskUniqueIds: null,
    EventAction: '',
    EventDate: '',
    EventType: 'New',
    LastPublishedRecordStatus: 'Active'
  }
]